version: "3"

services:
    mmr_model:
        build: .
        volumes:
            - ./app/:/mmr_model/app/
            - ./music/:/mmr_model/music/
        ports:
            - 5001:5001
        command: bash -c "python ./app/main.py"
